try {
    console.log("Đây là chức năng login")
} catch (error) {
    console.log(error)
}
